//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Leyer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Leyer.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید خارجی.
        /// </summary>
        internal static string FKeror {
            get {
                return ResourceManager.GetString("FKeror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایدی معتبر نیست.
        /// </summary>
        internal static string InvalidID {
            get {
                return ResourceManager.GetString("InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده وارد شده معتبر نیست.
        /// </summary>
        internal static string InvalidInputData {
            get {
                return ResourceManager.GetString("InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کتگوری یافت نشد.
        /// </summary>
        internal static string NoCategoryYet {
            get {
                return ResourceManager.GetString("NoCategoryYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ای هنوز ساخته نشده است.
        /// </summary>
        internal static string NoDataReult {
            get {
                return ResourceManager.GetString("NoDataReult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده یافت نشد.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خظایی رخ داده است.
        /// </summary>
        internal static string SomthingWrong {
            get {
                return ResourceManager.GetString("SomthingWrong", resourceCulture);
            }
        }
    }
}
